# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MtbProjStateId',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MtbProjTrailId',
            fields=[
                ('trailId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('stateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.MtbProjStateId')),
            ],
        ),
        migrations.CreateModel(
            name='SingletracksTrail',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('difficulty', models.TextField(default='Unknown')),
                ('rating', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('length', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TFid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('trail_id', models.IntegerField(default=None)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TFState',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TFStateArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('riding_area', models.TextField()),
                ('area_id', models.IntegerField(blank=True, default=None, null=True)),
                ('stateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFState')),
            ],
        ),
        migrations.AddField(
            model_name='tfid',
            name='areaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFStateArea'),
        ),
    ]
