# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrackstrail',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
