# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfid',
            old_name='id',
            new_name='Tid',
        ),
        migrations.RenameField(
            model_name='tfstatearea',
            old_name='id',
            new_name='Aid',
        ),
    ]
