# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0002_auto_20170405_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfstate',
            old_name='_id',
            new_name='Sid',
        ),
    ]
