# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0002_singletrackstrail_latitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('trail_id', models.IntegerField(default=None)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TFState',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TFStateArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('riding_area', models.TextField()),
                ('area_id', models.IntegerField(blank=True, default=None, null=True)),
                ('stateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFState')),
            ],
        ),
        migrations.RemoveField(
            model_name='singletrackstrail',
            name='id',
        ),
        migrations.AddField(
            model_name='singletrackstrail',
            name='key',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfid',
            name='areaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFStateArea'),
        ),
    ]
