# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0003_auto_20170405_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtbprojtrailid',
            old_name='trailId',
            new_name='mtrailId',
        ),
    ]
