# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0003_auto_20170315_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('trail_id', models.IntegerField(default=None)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TFState',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TFStateArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riding_area', models.TextField()),
                ('area_id', models.IntegerField(default=None)),
                ('stateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFState')),
            ],
        ),
        migrations.AddField(
            model_name='tfid',
            name='area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFStateArea'),
        ),
    ]
