# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0003_auto_20170315_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtbProjStateId',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MtbProjTrailId',
            fields=[
                ('trailId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('stateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.MtbProjStateId')),
            ],
        ),
    ]
