# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0004_auto_20170323_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletrackstrail',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='singletrackstrail',
            name='difficulty',
            field=models.TextField(default='Unknown'),
        ),
    ]
