# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0004_auto_20170324_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfid',
            old_name='area_id',
            new_name='areaId',
        ),
    ]
