# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0004_auto_20170408_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicates', models.BooleanField()),
                ('MTrailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.MtbProjTrailId')),
                ('SingleTracksId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.SingletracksTrail')),
                ('TfAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFStateArea')),
                ('TfTrailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFid')),
            ],
        ),
    ]
