# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0005_auto_20170324_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tfstatearea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
