# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0005_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='MTrailId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trailHQ.MtbProjTrailId'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='SingleTracksId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trailHQ.SingletracksTrail'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='TfAreaId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFStateArea'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='TfTrailId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trailHQ.TFid'),
        ),
    ]
