# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0006_auto_20170410_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtbProjTr',
            fields=[
                ('description', models.TextField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trailHQ.MtbProjTrailId')),
                ('orgs', models.TextField()),
                ('length', models.TextField()),
                ('ascent', models.TextField()),
                ('descent', models.TextField()),
                ('highElev', models.TextField()),
                ('lowElev', models.TextField()),
                ('avgGrade', models.TextField()),
                ('maxGrade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TFArea',
            fields=[
                ('regionDesc', models.TextField()),
                ('regionDiff', models.TextField()),
                ('localTrailGroup', models.TextField()),
                ('length', models.FloatField()),
                ('vertical', models.IntegerField()),
                ('numTrails', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trailHQ.TFStateArea')),
            ],
        ),
        migrations.CreateModel(
            name='TFTrail',
            fields=[
                ('description', models.TextField()),
                ('difficulty', models.TextField()),
                ('lastReport', models.TextField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trailHQ.TFid')),
                ('length', models.FloatField()),
                ('climb', models.IntegerField()),
                ('descent', models.IntegerField()),
                ('area', models.TextField()),
                ('trailType', models.TextField()),
            ],
        ),
    ]
