# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0007_mtbprojtr_tfarea_tftrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftrail',
            name='length',
            field=models.TextField(),
        ),
    ]
