# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0007_mtbprojtr_tfarea_tftrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtbprojtr',
            name='ascent',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtbprojtr',
            name='avgGrade',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtbprojtr',
            name='descent',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtbprojtr',
            name='highElev',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtbprojtr',
            name='length',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtbprojtr',
            name='lowElev',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtbprojtr',
            name='maxGrade',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtbprojtr',
            name='orgs',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mtbprojtr',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trailHQ.MtbProjTrailId'),
        ),
    ]
