# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0008_auto_20170425_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtbprojtr',
            old_name='id',
            new_name='Mid',
        ),
        migrations.RenameField(
            model_name='tfarea',
            old_name='id',
            new_name='Aid',
        ),
        migrations.RenameField(
            model_name='tftrail',
            old_name='id',
            new_name='Tid',
        ),
    ]
