# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0009_auto_20170426_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfarea',
            name='length',
            field=models.TextField(),
        ),
    ]
