# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0010_auto_20170426_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfarea',
            name='numTrails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tfarea',
            name='vertical',
            field=models.TextField(),
        ),
    ]
