# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0011_auto_20170426_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tftrail',
            name='avgTime',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
