# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0012_tftrail_avgtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftrail',
            name='climb',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tftrail',
            name='descent',
            field=models.TextField(),
        ),
    ]
