# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailHQ', '0013_auto_20170426_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtbprojtr',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfarea',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
